import os
import urllib.request
from urllib.parse import urlparse

# The presigned URL generated by boto3
PRESIGNED_URL: str = "http://localhost:9000/annotation-app-bucket/document-67afd4fc-4742-49e4-a270-32834713e6d5.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=admin%2F20250904%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250904T113954Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=34a90b6ce1c1345167e6451523c53ef09b35ca968ffd882d5946b7063c6c5b3a"

# File to upload
SCRIPT_FILE_PATH: str = os.path.abspath(__file__)

# Validate URL scheme for security
cleaned_url: str = PRESIGNED_URL.strip()
parsed_url = urlparse(cleaned_url)
if parsed_url.scheme not in ("http", "https"):
    raise ValueError("URL must use 'http' or 'https' scheme")

with open(SCRIPT_FILE_PATH, "rb") as file_handle:
    file_data: bytes = file_handle.read()

# Additional security check before making the request
if not cleaned_url.startswith(("http:", "https:")):
    raise ValueError("URL must start with 'http:' or 'https:'")

request = urllib.request.Request(cleaned_url, data=file_data, method="PUT")
request.add_header("Content-Type", "application/pdf")

with urllib.request.urlopen(request) as response:
    print("Status:", response.status)
    print("Response:", response.read().decode())

