// Generated by ts-to-zod
import { z } from "zod";

export const appErrorCodeSchema = z.union([z.literal("unknown_error"), z.literal("validation_error"), z.literal("invalid_input"), z.literal("database_unavailable"), z.literal("invalid_token"), z.literal("not_authenticated"), z.literal("not_authorized"), z.literal("invalid_credentials"), z.literal("not_in_group"), z.literal("email_not_verified"), z.literal("sharelink_invalid"), z.literal("sharelink_expired"), z.literal("membership_not_found"), z.literal("owner_cannot_leave_group"), z.literal("cannot_remove_permission_reason_default_group"), z.literal("cannot_remove_permission_reason_sharelink"), z.literal("username_taken"), z.literal("email_taken"), z.literal("sharelink_anonymous_disabled")]);

export const visibilitySchema = z.union([z.literal("private"), z.literal("restricted"), z.literal("public")]);

export const reactionTypeSchema = z.union([z.literal("like"), z.literal("dislike"), z.literal("laugh"), z.literal("confused"), z.literal("fire")]);

export const viewModeSchema = z.union([z.literal("restricted"), z.literal("public")]);

export const permissionSchema = z.union([z.literal("administrator"), z.literal("add_comments"), z.literal("remove_comments"), z.literal("view_restricted_comments"), z.literal("add_members"), z.literal("remove_members"), z.literal("manage_permissions"), z.literal("upload_documents"), z.literal("view_restricted_documents"), z.literal("delete_documents"), z.literal("remove_reactions"), z.literal("add_reactions"), z.literal("manage_tags")]);

export const appErrorSchema = z.object({
    status_code: z.number(),
    error_code: appErrorCodeSchema,
    detail: z.string()
});

export const commentSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.number().optional(),
    visibility: visibilitySchema,
    document_id: z.string(),
    user_id: z.number(),
    parent_id: z.number().optional().nullable(),
    content: z.string().optional().nullable(),
    annotation: z.record(z.string(), z.unknown()).optional()
});

export const commentCreateSchema = z.object({
    visibility: visibilitySchema,
    document_id: z.string(),
    parent_id: z.number().optional().nullable(),
    content: z.string().optional().nullable(),
    annotation: z.record(z.string(), z.unknown()).optional().nullable()
});

export const userReadSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.number(),
    username: z.string(),
    first_name: z.string().optional().nullable(),
    last_name: z.string().optional().nullable(),
    is_guest: z.boolean().optional()
});

export const reactionReadSchema = z.object({
    type: reactionTypeSchema,
    user: userReadSchema,
    comment_id: z.number()
});

export const tagReadSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.number(),
    document_id: z.string(),
    label: z.string(),
    description: z.string().nullable(),
    color: z.string()
});

export const commentFilterSchema = z.object({
    visibility: visibilitySchema,
    user_id: z.number(),
    document_id: z.string(),
    parent_id: z.number(),
    annotation: z.record(z.string(), z.unknown()),
    id: z.number()
});

export const commentTagsUpdateSchema = z.object({
    tag_ids: z.array(z.number())
});

export const commentUpdateSchema = z.object({
    visibility: visibilitySchema.optional().nullable(),
    content: z.string().optional().nullable(),
    annotation: z.record(z.string(), z.unknown()).optional().nullable()
});

export const documentSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.string().optional(),
    name: z.string(),
    s3_key: z.string(),
    size_bytes: z.number().optional(),
    visibility: visibilitySchema.optional(),
    view_mode: viewModeSchema.optional(),
    secret: z.string().optional(),
    group_id: z.string()
});

export const documentCreateSchema = z.object({
    visibility: visibilitySchema,
    name: z.string(),
    group_id: z.string()
});

export const documentFilterSchema = z.object({
    size_bytes: z.number(),
    group_id: z.string()
});

export const documentReadSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.string(),
    s3_key: z.string(),
    name: z.string(),
    group_id: z.string(),
    visibility: visibilitySchema,
    view_mode: viewModeSchema,
    tags: z.array(tagReadSchema)
});

export const documentTransferSchema = z.object({
    group_id: z.string()
});

export const globalJwtPayloadSchema = z.object({
    sub: z.string(),
    type: z.union([z.literal("access"), z.literal("refresh")]).optional().nullable(),
    scopes: z.array(z.string()).optional().nullable(),
    exp: z.string().optional().nullable(),
    iat: z.string().optional().nullable(),
    inner: z.string().optional().nullable()
});

export const groupSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.string().optional(),
    name: z.string(),
    secret: z.string().optional(),
    default_permissions: z.array(permissionSchema).optional()
});

export const groupCreateSchema = z.object({
    name: z.string(),
    default_permissions: z.array(permissionSchema)
});

export const groupFilterSchema = z.object({
    name: z.string(),
    member_count: z.number(),
    accepted: z.boolean()
});

export const groupReadSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.string(),
    name: z.string(),
    member_count: z.number(),
    document_count: z.number(),
    owner: userReadSchema.nullable(),
    default_permissions: z.array(permissionSchema)
});

export const groupTransferSchema = z.object({
    user_id: z.number()
});

export const groupUpdateSchema = z.object({
    name: z.string().optional().nullable(),
    default_permissions: z.array(permissionSchema).optional().nullable()
});

export const membershipSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    user_id: z.number(),
    group_id: z.string(),
    permissions: z.array(permissionSchema).optional(),
    is_owner: z.boolean().optional(),
    sharelink_id: z.number().optional().nullable(),
    accepted: z.boolean().optional()
});

export const membershipCreateSchema = z.object({
    user_id: z.number()
});

export const membershipFilterSchema = z.object({
    user_id: z.number(),
    group_id: z.string(),
    accepted: z.boolean(),
    sharelink_id: z.string()
});

export const membershipPermissionUpdateSchema = z.object({
    permissions: z.array(permissionSchema)
});

export const shareLinkReadNoTokenSchema = z.object({
    id: z.number(),
    permissions: z.array(permissionSchema),
    expires_at: z.string().optional().nullable(),
    allow_anonymous_access: z.boolean(),
    created_at: z.string(),
    updated_at: z.string(),
    group_id: z.string()
});

export const mousePositionEventSchema = z.object({
    user_id: z.number(),
    username: z.string(),
    x: z.number(),
    y: z.number(),
    page: z.number(),
    visible: z.boolean().optional()
});

export const mousePositionInputSchema = z.object({
    x: z.number(),
    y: z.number(),
    page: z.number(),
    visible: z.boolean().optional()
});

export const filterSchema = z.record(z.string(), z.unknown()).and(z.object({
    field: z.string(),
    operator: z.union([z.literal("=="), z.literal(">="), z.literal("<="), z.literal(">"), z.literal("<"), z.literal("ilike"), z.literal("like"), z.literal("exists"), z.literal("!="), z.literal("in"), z.literal("notin")]),
    value: z.string()
}));

export const reactionCreateSchema = z.object({
    type: reactionTypeSchema
});

export const shareLinkCreateSchema = z.object({
    permissions: z.array(permissionSchema),
    allow_anonymous_access: z.boolean().optional(),
    expires_at: z.string().optional().nullable(),
    label: z.string().optional().nullable()
});

export const shareLinkFilterSchema = z.object({
    label: z.string(),
    expires_at: z.string(),
    author_id: z.number()
});

export const shareLinkReadSchema = z.object({
    id: z.number(),
    permissions: z.array(permissionSchema),
    expires_at: z.string().optional().nullable(),
    allow_anonymous_access: z.boolean(),
    created_at: z.string(),
    updated_at: z.string(),
    label: z.string().optional().nullable(),
    token: z.string(),
    author: userReadSchema.nullable(),
    group_id: z.string(),
    num_memberships: z.number()
});

export const shareLinkReadFromTokenSchema = z.object({
    id: z.number(),
    permissions: z.array(permissionSchema),
    expires_at: z.string().optional().nullable(),
    allow_anonymous_access: z.boolean(),
    created_at: z.string(),
    updated_at: z.string(),
    group: groupReadSchema,
    token: z.string()
});

export const shareLinkUpdateSchema = z.object({
    permissions: z.array(permissionSchema).optional().nullable(),
    expires_at: z.string().optional().nullable(),
    allow_anonymous_access: z.boolean().optional().nullable(),
    label: z.string().optional().nullable(),
    rotate_token: z.boolean().optional().nullable()
});

export const sortSchema = z.object({
    field: z.string(),
    direction: z.union([z.literal("asc"), z.literal("desc")])
});

export const tagCreateSchema = z.object({
    label: z.string(),
    description: z.string().optional().nullable(),
    color: z.string()
});

export const tagUpdateSchema = z.object({
    label: z.string().optional().nullable(),
    description: z.string().optional().nullable(),
    color: z.string().optional().nullable()
});

export const tokenSchema = z.object({
    access_token: z.string(),
    refresh_token: z.string().optional().nullable(),
    token_type: z.string()
});

export const userSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.number().optional(),
    username: z.string(),
    first_name: z.string().optional().nullable(),
    last_name: z.string().optional().nullable(),
    password: z.string().optional().nullable(),
    email: z.string().optional().nullable(),
    verified: z.boolean().optional(),
    is_guest: z.boolean().optional(),
    secret: z.string().optional()
});

export const userCreateSchema = z.object({
    token: z.string().optional().nullable(),
    username: z.string(),
    password: z.string().optional().nullable(),
    email: z.string().optional().nullable(),
    first_name: z.string().optional().nullable(),
    last_name: z.string().optional().nullable()
});

export const userFilterSchema = z.object({
    username: z.string(),
    first_name: z.string(),
    last_name: z.string(),
    group_id: z.string()
});

export const userJwtPayloadSchema = z.object({
    sub: z.string(),
    exp: z.string().optional().nullable(),
    iat: z.string().optional().nullable()
});

export const userPrivateSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.number(),
    username: z.string(),
    first_name: z.string().optional().nullable(),
    last_name: z.string().optional().nullable(),
    is_guest: z.boolean().optional(),
    email: z.string().optional().nullable()
});

export const userUpdateSchema = z.object({
    username: z.string().optional().nullable(),
    new_password: z.string().optional().nullable(),
    old_password: z.string().optional().nullable(),
    email: z.string().optional().nullable(),
    first_name: z.string().optional().nullable(),
    last_name: z.string().optional().nullable()
});

export const viewModeChangedEventSchema = z.object({
    document_id: z.string(),
    view_mode: viewModeSchema
});

export const commentReadSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.number(),
    visibility: visibilitySchema,
    user: userReadSchema.nullable(),
    parent_id: z.number().nullable(),
    annotation: z.record(z.string(), z.unknown()).nullable(),
    content: z.string().nullable(),
    num_replies: z.number(),
    reactions: z.array(reactionReadSchema),
    tags: z.array(tagReadSchema)
});

export const membershipReadSchema = z.object({
    permissions: z.array(permissionSchema),
    user: userReadSchema,
    group: groupReadSchema,
    is_owner: z.boolean(),
    accepted: z.boolean(),
    share_link: shareLinkReadNoTokenSchema.nullable()
});

export const paginatedBaseSchema = z.object({
    data: z.array(z.unknown()),
    total: z.number(),
    offset: z.number(),
    limit: z.number(),
    filters: z.array(filterSchema).optional(),
    order_by: z.array(z.string()).optional(),
    excluded_fields: z.array(z.string()).optional()
});

export const commentEventSchema = z.object({
    event_id: z.string(),
    published_at: z.string().optional(),
    payload: commentReadSchema.nullable(),
    resource_id: z.number().nullable(),
    resource: z.string().nullable(),
    type: z.string(),
    originating_connection_id: z.string().optional().nullable()
});
