// Generated by ts-to-zod
import { z } from "zod";
import { type CommentRead } from "./types";

export const visibilitySchema = z.union([z.literal("private"), z.literal("restricted"), z.literal("public")]);

export const reactionTypeSchema = z.union([z.literal("like"), z.literal("dislike"), z.literal("laugh"), z.literal("confused"), z.literal("fire")]);

export const visibility1Schema = z.union([z.literal("private"), z.literal("restricted"), z.literal("public")]);

export const viewModeSchema = z.union([z.literal("private"), z.literal("anonymous"), z.literal("public")]);

export const permissionSchema = z.union([z.literal("administrator"), z.literal("add_comments"), z.literal("remove_comments"), z.literal("view_public_comments"), z.literal("view_restricted_comments"), z.literal("add_members"), z.literal("remove_members"), z.literal("manage_permissions"), z.literal("upload_documents"), z.literal("view_restricted_documents"), z.literal("delete_documents"), z.literal("remove_reactions"), z.literal("add_reactions"), z.literal("manage_share_links")]);

export const commentSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.number().optional(),
    visibility: visibilitySchema,
    document_id: z.string(),
    user_id: z.number(),
    parent_id: z.number().optional().nullable(),
    content: z.string().optional().nullable(),
    annotation: z.record(z.string(), z.unknown()).optional()
});

export const commentCreateSchema = z.object({
    visibility: visibilitySchema,
    document_id: z.string(),
    parent_id: z.number().optional().nullable(),
    content: z.string().optional().nullable(),
    annotation: z.record(z.string(), z.unknown()).optional().nullable()
});

export const commentFilterSchema = z.object({
    visibility: visibilitySchema
});

export const userReadSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.number(),
    username: z.string(),
    first_name: z.string().optional().nullable(),
    last_name: z.string().optional().nullable()
});

export const reactionReadSchema = z.object({
    type: reactionTypeSchema,
    user: userReadSchema,
    comment_id: z.number()
});

export const commentUpdateSchema = z.object({
    visibility: visibilitySchema.optional().nullable(),
    content: z.string().optional().nullable(),
    annotation: z.record(z.string(), z.unknown()).optional().nullable()
});

export const documentSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.string().optional(),
    s3_key: z.string(),
    size_bytes: z.number().optional(),
    visibility: visibility1Schema.optional(),
    view_mode: viewModeSchema.optional(),
    secret: z.string().optional(),
    group_id: z.string()
});

export const documentCreateSchema = z.object({
    visibility: visibilitySchema,
    group_id: z.string()
});

export const documentFilterSchema = z.object({
    size_bytes: z.number(),
    group_id: z.string()
});

export const documentReadSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.string(),
    s3_key: z.string(),
    group_id: z.string(),
    visibility: visibilitySchema
});

export const documentTransferSchema = z.object({
    group_id: z.string()
});

export const globalJwtPayloadSchema = z.object({
    sub: z.string(),
    type: z.union([z.literal("access"), z.literal("refresh")]).optional().nullable(),
    exp: z.string().optional().nullable(),
    iat: z.string().optional().nullable(),
    inner: z.string().optional().nullable()
});

export const groupSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.string().optional(),
    name: z.string(),
    secret: z.string().optional(),
    default_permissions: z.array(permissionSchema).optional()
});

export const groupCreateSchema = z.object({
    name: z.string(),
    default_permissions: z.array(permissionSchema)
});

export const groupFilterSchema = z.object({
    name: z.string(),
    member_count: z.number(),
    accepted: z.boolean()
});

export const groupMembershipFilterSchema = z.object({
    user_id: z.number()
});

export const groupMembershipReadSchema = z.object({
    permissions: z.array(permissionSchema),
    user: userReadSchema,
    is_owner: z.boolean(),
    accepted: z.boolean(),
    group_id: z.string()
});

export const groupReadSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.string(),
    name: z.string(),
    member_count: z.number(),
    owner: userReadSchema.nullable()
});

export const groupUpdateSchema = z.object({
    name: z.string().optional().nullable(),
    default_permissions: z.array(permissionSchema).optional().nullable()
});

export const membershipSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    user_id: z.number(),
    group_id: z.string(),
    permissions: z.array(permissionSchema).optional(),
    is_owner: z.boolean().optional(),
    accepted: z.boolean().optional()
});

export const filterSchema = z.record(z.string(), z.unknown()).and(z.object({
    field: z.string(),
    operator: z.union([z.literal("=="), z.literal(">="), z.literal("<="), z.literal(">"), z.literal("<"), z.literal("ilike"), z.literal("like"), z.literal("exists"), z.literal("!=")]),
    value: z.string()
}));

export const reactionCreateSchema = z.object({
    type: reactionTypeSchema
});

export const shareLinkCreateSchema = z.object({
    permissions: z.array(permissionSchema),
    expires_at: z.string().optional().nullable(),
    label: z.string().optional().nullable()
});

export const shareLinkReadSchema = z.object({
    id: z.number(),
    permissions: z.array(permissionSchema),
    expires_at: z.string().optional().nullable(),
    label: z.string().optional().nullable(),
    token: z.string(),
    author: userReadSchema,
    group_id: z.string()
});

export const shareLinkUpdateSchema = z.object({
    permissions: z.array(permissionSchema).optional().nullable(),
    expires_at: z.string().optional().nullable(),
    label: z.string().optional().nullable(),
    rotate_token: z.boolean().optional().nullable()
});

export const sortSchema = z.object({
    field: z.string(),
    direction: z.union([z.literal("asc"), z.literal("desc")])
});

export const tokenSchema = z.object({
    access_token: z.string(),
    refresh_token: z.string().optional().nullable(),
    token_type: z.string()
});

export const userSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.number().optional(),
    username: z.string(),
    first_name: z.string().optional().nullable(),
    last_name: z.string().optional().nullable(),
    password: z.string(),
    email: z.string(),
    verified: z.boolean().optional(),
    secret: z.string().optional()
});

export const userCreateSchema = z.object({
    username: z.string(),
    password: z.string(),
    email: z.string(),
    first_name: z.string().optional().nullable(),
    last_name: z.string().optional().nullable()
});

export const userFilterSchema = z.object({
    username: z.string(),
    first_name: z.string(),
    last_name: z.string()
});

export const userJwtPayloadSchema = z.object({
    sub: z.string(),
    exp: z.string().optional().nullable(),
    iat: z.string().optional().nullable()
});

export const userMembershipReadSchema = z.object({
    permissions: z.array(permissionSchema),
    group: groupReadSchema,
    is_owner: z.boolean(),
    accepted: z.boolean(),
    user_id: z.number()
});

export const userPrivateSchema = z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.number(),
    username: z.string(),
    first_name: z.string().optional().nullable(),
    last_name: z.string().optional().nullable(),
    email: z.string()
});

export const userUpdateSchema = z.object({
    username: z.string().optional().nullable(),
    new_password: z.string().optional().nullable(),
    old_password: z.string().optional().nullable(),
    email: z.string().optional().nullable(),
    first_name: z.string().optional().nullable(),
    last_name: z.string().optional().nullable()
});

export const commentReadSchema: z.ZodSchema<CommentRead> = z.lazy(() => z.object({
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
    id: z.number(),
    visibility: visibilitySchema,
    user: userReadSchema.nullable(),
    annotation: z.record(z.string(), z.unknown()),
    content: z.string().nullable(),
    replies: z.array(commentReadSchema),
    reactions: z.array(reactionReadSchema)
}));

export const paginatedBaseSchema = z.object({
    data: z.array(z.unknown()),
    total: z.number(),
    offset: z.number(),
    limit: z.number(),
    filters: z.array(filterSchema).optional(),
    order_by: z.array(z.string()).optional()
});
