"""consolidated

Revision ID: 0c5025fb1337
Revises: 
Create Date: 2025-10-25 20:01:37.500291

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c5025fb1337'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted for circular dependency ###
    sa.Enum('PRIVATE', 'RESTRICTED', 'PUBLIC', name='visibility').create(op.get_bind())
    sa.Enum('PRIVATE', 'ANONYMOUS', 'PUBLIC', name='viewmode').create(op.get_bind())

    # Create the 'group' table first
    op.create_table('group',
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('default_permissions', sa.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_name'), ['name'], unique=True)

    # Create the 'user' table next
    op.create_table('user',
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('verified', sa.Boolean(), nullable=False),
        sa.Column('secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # Create the 'document' table after 'group' and 'user'
    op.create_table('document',
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('s3_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('size_bytes', sa.Integer(), nullable=False),
        sa.Column('view_mode', postgresql.ENUM('PRIVATE', 'ANONYMOUS', 'PUBLIC', name='viewmode', create_type=False), nullable=False),
        sa.Column('secret', sa.UUID(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.CheckConstraint('NOT (user_id IS NOT NULL AND group_id IS NOT NULL)', name='owner_xor'),
        sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )

    # Create the 'annotation' table before 'comment'
    op.create_table('annotation',
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=False),
        sa.Column('comment_id', sa.Integer(), nullable=True),  # Foreign key deferred
        sa.Column('anon_id', sa.UUID(), nullable=True),
        sa.Column('anon_alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Create the 'comment' table after 'annotation'
    op.create_table('comment',
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('visibility', postgresql.ENUM('PRIVATE', 'RESTRICTED', 'PUBLIC', name='visibility', create_type=False), nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=False),
        sa.Column('annotation_id', sa.Integer(), nullable=True),  # Foreign key deferred
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('anon_id', sa.UUID(), nullable=True),
        sa.Column('endorsements', sa.Integer(), nullable=False),
        sa.Column('anon_alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )

    # Create the 'membership' table after 'group' and 'user'
    op.create_table('membership',
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('permissions', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('is_owner', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'group_id')
    )

    # Add the foreign key to 'comment_id' in the 'annotation' table
    op.create_foreign_key(
        'fk_annotation_comment_id_comment',
        source_table='annotation',
        referent_table='comment',
        local_cols=['comment_id'],
        remote_cols=['id'],
        ondelete='CASCADE'
    )

    # Add the foreign key to 'annotation_id' in the 'comment' table
    op.create_foreign_key(
        'fk_comment_annotation_id_annotation',
        source_table='comment',
        referent_table='annotation',
        local_cols=['annotation_id'],
        remote_cols=['id'],
        ondelete='CASCADE'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_s3_key'))

    op.drop_table('document')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_name'))

    op.drop_table('group')
    op.drop_table('comment')
    op.drop_table('annotation')
    sa.Enum('PRIVATE', 'ANONYMOUS', 'PUBLIC', name='viewmode').drop(op.get_bind())
    sa.Enum('PRIVATE', 'RESTRICTED', 'PUBLIC', name='visibility').drop(op.get_bind())
    # ### end Alembic commands ###
