"""add sharelink ref to membership

Revision ID: 174194a9a028
Revises: b86f68119066
Create Date: 2025-11-27 10:07:39.978449

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174194a9a028'
down_revision: Union[str, None] = 'b86f68119066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sharelink_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sharelink', ['sharelink_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sharelink_id')

    # ### end Alembic commands ###
