"""rename s3_key to storage_key

Revision ID: 2023353843ad
Revises: 3c46263e120f
Create Date: 2026-02-27 18:25:46.403477

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2023353843ad'
down_revision: Union[str, None] = '3c46263e120f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('s3_key', new_column_name='storage_key')
        batch_op.drop_index('ix_document_s3_key')
        batch_op.create_index(batch_op.f('ix_document_storage_key'), ['storage_key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_storage_key'))
        batch_op.create_index('ix_document_s3_key', ['s3_key'], unique=True)
        batch_op.alter_column('storage_key', new_column_name='s3_key')

    # ### end Alembic commands ###
