"""add indexes and comment user cascade

Revision ID: 2903a6e3b722
Revises: 422f92aa4211
Create Date: 2026-02-24 00:18:19.152985

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2903a6e3b722'
down_revision: Union[str, None] = '422f92aa4211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_comment_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comment_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_group_id'), ['group_id'], unique=False)

    with op.batch_alter_table('groupreaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groupreaction_group_id'), ['group_id'], unique=False)

    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reaction_group_reaction_id'), ['group_reaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reaction_group_reaction_id'))

    with op.batch_alter_table('groupreaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groupreaction_group_id'))

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_group_id'))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comment_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_comment_user_id'))
        batch_op.drop_index(batch_op.f('ix_comment_parent_id'))
        batch_op.drop_index(batch_op.f('ix_comment_document_id'))

    # ### end Alembic commands ###
