"""add document order

Revision ID: 39b92b5cd04e
Revises: 2023353843ad
Create Date: 2026-02-28 14:47:50.748622

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39b92b5cd04e'
down_revision: Union[str, None] = '2023353843ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add order column as nullable first so existing rows can be backfilled
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # Backfill: assign 0-based order within each group by created_at
    op.get_bind().execute(
        sa.text(
            """
            UPDATE document
            SET "order" = sub.rn
            FROM (
                SELECT id,
                       ROW_NUMBER() OVER (
                           PARTITION BY group_id
                           ORDER BY created_at ASC
                       ) - 1 AS rn
                FROM document
            ) sub
            WHERE document.id = sub.id
            """
        )
    )

    # Now make the column non-nullable
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('order', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
