"""add_index_on_taskresponse_user_id

Revision ID: 3c46263e120f
Revises: 84504dcfd253
Create Date: 2026-02-24 15:55:45.596343

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c46263e120f'
down_revision: Union[str, None] = '84504dcfd253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskresponse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taskresponse_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskresponse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taskresponse_user_id'))

    # ### end Alembic commands ###
