"""simplify permissions and document visibility

Remove old granular permissions (remove_comments, add_members,
remove_members, manage_permissions, upload_documents,
view_restricted_documents, delete_documents, remove_reactions,
manage_tags) from membership, group, and sharelink tables.
Convert documents with 'restricted' visibility to 'public'.

Revision ID: 422f92aa4211
Revises: b2c3d4e5f6g7
Create Date: 2026-02-21 03:01:00.440424

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422f92aa4211'
down_revision: Union[str, None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Permissions that no longer exist as standalone values.
REMOVED_PERMISSIONS = [
    "remove_comments",
    "add_members",
    "remove_members",
    "manage_permissions",
    "upload_documents",
    "view_restricted_documents",
    "delete_documents",
    "remove_reactions",
    "manage_tags",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Strip removed permissions from all permission array columns
    for perm in REMOVED_PERMISSIONS:
        op.execute(
            sa.text(
                "UPDATE membership "
                "SET permissions = array_remove(permissions, :perm) "
                "WHERE permissions IS NOT NULL"
            ).bindparams(perm=perm)
        )
        op.execute(
            sa.text(
                'UPDATE "group" '
                "SET default_permissions = array_remove("
                "default_permissions, :perm) "
                "WHERE default_permissions IS NOT NULL"
            ).bindparams(perm=perm)
        )
        op.execute(
            sa.text(
                "UPDATE sharelink "
                "SET permissions = array_remove(permissions, :perm) "
                "WHERE permissions IS NOT NULL"
            ).bindparams(perm=perm)
        )

    # Convert restricted documents to public
    op.execute(
        sa.text(
            "UPDATE document "
            "SET visibility = 'public' "
            "WHERE visibility = 'restricted'"
        )
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
