"""normalize emails lowercase and min username length

Revision ID: 5492a960cd49
Revises: 39b92b5cd04e
Create Date: 2026-03-03 21:35:30.045527

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5492a960cd49'
down_revision: Union[str, None] = '39b92b5cd04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # M6: Normalize all existing emails to lowercase
    op.execute(
        'UPDATE "user" SET email = LOWER(TRIM(email))'
        " WHERE email IS NOT NULL"
    )

    # L6: Add CHECK constraint for minimum username length (3)
    op.create_check_constraint(
        "ck_user_username_min_length",
        "user",
        sa.text("LENGTH(username) >= 3"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_user_username_min_length", "user", type_="check"
    )
    # Note: email lowercasing is not reversible
    # ### end Alembic commands ###
