"""add sharelink anonymous flag

Revision ID: c64877703f21
Revises: 9b02b0a589c1
Create Date: 2025-11-25 15:30:26.562615

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64877703f21'
down_revision: Union[str, None] = '9b02b0a589c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sharelink', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_anonymous_access', sa.Boolean(), server_default='false', nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sharelink', schema=None) as batch_op:
        batch_op.drop_column('allow_anonymous_access')

    # ### end Alembic commands ###
