"""make group non nullable on documents

Revision ID: d08f30ac3075
Revises: c094026c1c27
Create Date: 2025-10-27 03:27:57.354831

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08f30ac3075'
down_revision: Union[str, None] = 'c094026c1c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_document_group_id_group'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_document_group_id_group'), 'group', ['group_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
