"""add tag order

Revision ID: e650017110fc
Revises: 02225ce72602
Create Date: 2025-12-06 21:38:30.386153

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e650017110fc'
down_revision: Union[str, None] = '02225ce72602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commenttag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # Assign order values to existing comment tag links
    connection = op.get_bind()
    
    # Get all comment_ids that have tags
    result = connection.execute(
        sa.text("SELECT DISTINCT comment_id FROM commenttag ORDER BY comment_id")
    )
    comment_ids = [row[0] for row in result]
    
    # For each comment, assign sequential order values to its tags
    for comment_id in comment_ids:
        tag_result = connection.execute(
            sa.text("SELECT tag_id FROM commenttag WHERE comment_id = :comment_id ORDER BY tag_id"),
            {"comment_id": comment_id}
        )
        tags = [row[0] for row in tag_result]
        
        for idx, tag_id in enumerate(tags):
            connection.execute(
                sa.text("UPDATE commenttag SET \"order\" = :order WHERE comment_id = :comment_id AND tag_id = :tag_id"),
                {"order": idx, "comment_id": comment_id, "tag_id": tag_id}
            )
    
    # Make the column non-nullable after setting values
    with op.batch_alter_table('commenttag', schema=None) as batch_op:
        batch_op.alter_column('order', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commenttag', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
