"""db defaults

Revision ID: efdfef87f442
Revises: 0c5025fb1337
Create Date: 2025-10-26 00:00:48.976279

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efdfef87f442'
down_revision: Union[str, None] = '0c5025fb1337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.alter_column('comment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_annotation_document_id_document'), type_='foreignkey')
        batch_op.drop_column('anon_id')
        batch_op.drop_column('anon_alias')
        batch_op.drop_column('document_id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_annotation_id_annotation'), type_='foreignkey')
        batch_op.drop_column('annotation_id')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('view_mode',
               existing_type=postgresql.ENUM('PRIVATE', 'ANONYMOUS', 'PUBLIC', name='viewmode'),
               type_=sa.String(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_document_s3_key'), ['s3_key'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('secret',
               existing_type=sa.VARCHAR(),
               nullable=True)

    sa.Enum('PRIVATE', 'ANONYMOUS', 'PUBLIC', name='viewmode').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PRIVATE', 'ANONYMOUS', 'PUBLIC', name='viewmode').create(op.get_bind())
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('secret',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_s3_key'))
        batch_op.alter_column('view_mode',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PRIVATE', 'ANONYMOUS', 'PUBLIC', name='viewmode'),
               nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annotation_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comment_annotation_id_annotation'), 'annotation', ['annotation_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('anon_alias', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('anon_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_annotation_document_id_document'), 'document', ['document_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('comment_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
