@startuml DocumentSharing

' Styling
skinparam componentStyle rectangle
skinparam component {
    ArrowThickness 1
}
skinparam linetype ortho

' ========== TABLES ==========

class User {
    - id : int [PK]
    - username : string [UNIQUE, INDEXED]
    - first_name : string [NULLABLE]
    - last_name : string [NULLABLE]
    - password : string
    - email : string [UNIQUE, INDEXED]
    - verified : bool [DEFAULT: false]
    - secret : string [DEFAULT: gen_random_uuid]
    - created_at : datetime
    - updated_at : datetime
    ____
        **Relationships**
        # documents: list[Document]
        # memberships: list[Membership]
        # annotations: list[Annotation]
        # groups: list[Group]
}

class Group {
    - id : int [PK]
    - name : string [UNIQUE, INDEXED]
    - secret : string [DEFAULT: gen_random_uuid]
    - created_at : datetime
    - updated_at : datetime
    ____
        **Relationships**
        # owner: User
        # documents: list[Document]
        # memberships: list[Membership]
    ____
        **Column Properties**
        # member_count: int
}

enum Permission {
    administrator
    add_annotations
    view_public_annotations
    view_public_annotation_user
    view_restricted_annotations
    view_restricted_annotation_user
    endorse_comments
    manage_members
    manage_permissions
    upload_documents
    delete_documents
    modify_documents
}

enum ViewMode {
    private
    anonymous
    public
}

class Membership {
    - user_id : int [PK, FK]
    - group_id : int [PK, FK]
    - permissions: set[Permission]
    - created_at : datetime
    - updated_at : datetime
    ____
        **Relationships**
        # user: User
        # group: Group
}

class Document {
    - id : int [PK]
    - s3_key : string
    - size_bytes : int
    - view_mode : ViewMode
    - user_id : int [FK, NULLABLE]
    - group_id : int [FK, NULLABLE]
    - secret : uuid
    - created_at : datetime
    - updated_at : datetime
    ____
        **Relationships**
        # user: User [nullable]
        # group: Group [nullable]
        # annotations: list[Annotation]
    ____
        **Constraints**
        # owner_xor: user_id XOR group_id
}

enum Visibility {
    private
    restricted
    public
}

class Annotation {
    - id : int [PK]
    - document_id : int [FK]
    - comment_id : int [FK]
    - user_id : int [FK, NULLABLE]
    - anon_id : uuid
    - anon_alias : string [NULLABLE]
    - meta_data : jsonb
    - created_at : datetime
    - updated_at : datetime
    ____
        **Relationships**
        # document: Document
        # user: User [nullable]
        # comment: Comment
}

class Comment {
    - id : int [PK]
    - visibility : Visibility
    - document_id : int [FK]
    - annotation_id : int [FK, NULLABLE]
    - user_id : int [FK, NULLABLE]
    - anon_id : uuid
    - endorsements : int
    - anon_alias : string [NULLABLE]
    - parent_id : int [FK, NULLABLE]
    - content : string [NULLABLE]
    - created_at : datetime
    - updated_at : datetime
    ____
        **Relationships**
        # document: Document
        # annotation: Annotation [nullable]
        # user: User [nullable]
        # parent: Comment [nullable]
        # replies: list[Comment]
}

' ========== RELATIONSHIPS ==========

User -d-> Document
User -r-> Membership

Group -u-> Membership
Group -l-> Document


Membership -[hidden]r-> Permission

Comment -[hidden]l-> Visibility
Document -[hidden]l-> ViewMode
Annotation <-l- Comment
Document -d-> Comment

@enduml
