// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * L​o​g​i​n
	 */
	login: string
	/**
	 * L​o​g​o​u​t
	 */
	logout: string
	/**
	 * C​o​n​t​a​c​t
	 */
	contact: string
	/**
	 * I​m​p​r​i​n​t
	 */
	imprint: string
	/**
	 * R​e​g​i​s​t​e​r
	 */
	register: string
	/**
	 * U​s​e​r​n​a​m​e
	 */
	username: string
	/**
	 * E​m​a​i​l
	 */
	email: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	password: string
	/**
	 * F​i​r​s​t​ ​N​a​m​e
	 */
	firstName: string
	/**
	 * L​a​s​t​ ​N​a​m​e
	 */
	lastName: string
	/**
	 * C​o​n​f​i​r​m​ ​P​a​s​s​w​o​r​d
	 */
	confirmPassword: string
	/**
	 * U​s​e​r​n​a​m​e​ ​o​r​ ​E​m​a​i​l
	 */
	usernameOrEmail: string
	/**
	 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?​ ​L​o​g​i​n
	 */
	alreadyHaveAccount: string
	/**
	 * N​e​e​d​ ​a​n​ ​a​c​c​o​u​n​t​?​ ​R​e​g​i​s​t​e​r
	 */
	needAccount: string
	/**
	 * E​m​a​i​l​ ​v​e​r​i​f​i​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!​ ​Y​o​u​r​ ​a​c​c​o​u​n​t​ ​i​s​ ​n​o​w​ ​a​c​t​i​v​a​t​e​d​.
	 */
	emailVerified: string
	/**
	 * M​y​ ​G​r​o​u​p​s
	 */
	myGroups: string
	group: {
		/**
		 * D​o​c​u​m​e​n​t​s
		 */
		documents: string
		/**
		 * M​e​m​b​e​r​s
		 */
		members: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		memberships: {
			/**
			 * O​w​n​e​r
			 */
			owner: string
			/**
			 * M​e​m​b​e​r​s​h​i​p​s
			 */
			label: string
			/**
			 * A​c​c​e​p​t​e​d
			 */
			accepted: string
			/**
			 * I​n​v​i​t​e​d
			 */
			invited: string
		}
	}
	permissionGroups: {
		/**
		 * A​d​m​i​n​i​s​t​r​a​t​i​o​n
		 */
		administration: string
		/**
		 * C​o​m​m​e​n​t​s
		 */
		comments: string
		/**
		 * D​o​c​u​m​e​n​t​s
		 */
		documents: string
		/**
		 * M​e​m​b​e​r​s
		 */
		members: string
		/**
		 * R​e​a​c​t​i​o​n​s
		 */
		reactions: string
		/**
		 * S​h​a​r​e​ ​L​i​n​k​s
		 */
		shareLinks: string
	}
	permissions: {
		/**
		 * P​e​r​m​i​s​s​i​o​n​s
		 */
		label: string
		/**
		 * F​u​l​l​ ​a​d​m​i​n​i​s​t​r​a​t​i​v​e​ ​a​c​c​e​s​s
		 */
		administrator: string
		/**
		 * A​d​d​ ​c​o​m​m​e​n​t​s
		 */
		add_comments: string
		/**
		 * R​e​m​o​v​e​ ​c​o​m​m​e​n​t​s
		 */
		remove_comments: string
		/**
		 * V​i​e​w​ ​p​u​b​l​i​c​ ​c​o​m​m​e​n​t​s
		 */
		view_public_comments: string
		/**
		 * V​i​e​w​ ​r​e​s​t​r​i​c​t​e​d​ ​c​o​m​m​e​n​t​s
		 */
		view_restricted_comments: string
		/**
		 * A​d​d​ ​m​e​m​b​e​r​s
		 */
		add_members: string
		/**
		 * R​e​m​o​v​e​ ​m​e​m​b​e​r​s
		 */
		remove_members: string
		/**
		 * M​a​n​a​g​e​ ​p​e​r​m​i​s​s​i​o​n​s
		 */
		manage_permissions: string
		/**
		 * U​p​l​o​a​d​ ​d​o​c​u​m​e​n​t​s
		 */
		upload_documents: string
		/**
		 * V​i​e​w​ ​r​e​s​t​r​i​c​t​e​d​ ​d​o​c​u​m​e​n​t​s
		 */
		view_restricted_documents: string
		/**
		 * D​e​l​e​t​e​ ​d​o​c​u​m​e​n​t​s
		 */
		delete_documents: string
		/**
		 * R​e​m​o​v​e​ ​r​e​a​c​t​i​o​n​s
		 */
		remove_reactions: string
		/**
		 * A​d​d​ ​r​e​a​c​t​i​o​n​s
		 */
		add_reactions: string
		/**
		 * M​a​n​a​g​e​ ​s​h​a​r​e​ ​l​i​n​k​s
		 */
		manage_share_links: string
	}
	/**
	 * U​s​e​r
	 */
	user: string
	/**
	 * S​t​a​t​u​s
	 */
	status: string
	/**
	 * A​d​d
	 */
	add: string
	/**
	 * R​e​m​o​v​e
	 */
	remove: string
}

export type TranslationFunctions = {
	/**
	 * Login
	 */
	login: () => LocalizedString
	/**
	 * Logout
	 */
	logout: () => LocalizedString
	/**
	 * Contact
	 */
	contact: () => LocalizedString
	/**
	 * Imprint
	 */
	imprint: () => LocalizedString
	/**
	 * Register
	 */
	register: () => LocalizedString
	/**
	 * Username
	 */
	username: () => LocalizedString
	/**
	 * Email
	 */
	email: () => LocalizedString
	/**
	 * Password
	 */
	password: () => LocalizedString
	/**
	 * First Name
	 */
	firstName: () => LocalizedString
	/**
	 * Last Name
	 */
	lastName: () => LocalizedString
	/**
	 * Confirm Password
	 */
	confirmPassword: () => LocalizedString
	/**
	 * Username or Email
	 */
	usernameOrEmail: () => LocalizedString
	/**
	 * Already have an account? Login
	 */
	alreadyHaveAccount: () => LocalizedString
	/**
	 * Need an account? Register
	 */
	needAccount: () => LocalizedString
	/**
	 * Email verified successfully! Your account is now activated.
	 */
	emailVerified: () => LocalizedString
	/**
	 * My Groups
	 */
	myGroups: () => LocalizedString
	group: {
		/**
		 * Documents
		 */
		documents: () => LocalizedString
		/**
		 * Members
		 */
		members: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		memberships: {
			/**
			 * Owner
			 */
			owner: () => LocalizedString
			/**
			 * Memberships
			 */
			label: () => LocalizedString
			/**
			 * Accepted
			 */
			accepted: () => LocalizedString
			/**
			 * Invited
			 */
			invited: () => LocalizedString
		}
	}
	permissionGroups: {
		/**
		 * Administration
		 */
		administration: () => LocalizedString
		/**
		 * Comments
		 */
		comments: () => LocalizedString
		/**
		 * Documents
		 */
		documents: () => LocalizedString
		/**
		 * Members
		 */
		members: () => LocalizedString
		/**
		 * Reactions
		 */
		reactions: () => LocalizedString
		/**
		 * Share Links
		 */
		shareLinks: () => LocalizedString
	}
	permissions: {
		/**
		 * Permissions
		 */
		label: () => LocalizedString
		/**
		 * Full administrative access
		 */
		administrator: () => LocalizedString
		/**
		 * Add comments
		 */
		add_comments: () => LocalizedString
		/**
		 * Remove comments
		 */
		remove_comments: () => LocalizedString
		/**
		 * View public comments
		 */
		view_public_comments: () => LocalizedString
		/**
		 * View restricted comments
		 */
		view_restricted_comments: () => LocalizedString
		/**
		 * Add members
		 */
		add_members: () => LocalizedString
		/**
		 * Remove members
		 */
		remove_members: () => LocalizedString
		/**
		 * Manage permissions
		 */
		manage_permissions: () => LocalizedString
		/**
		 * Upload documents
		 */
		upload_documents: () => LocalizedString
		/**
		 * View restricted documents
		 */
		view_restricted_documents: () => LocalizedString
		/**
		 * Delete documents
		 */
		delete_documents: () => LocalizedString
		/**
		 * Remove reactions
		 */
		remove_reactions: () => LocalizedString
		/**
		 * Add reactions
		 */
		add_reactions: () => LocalizedString
		/**
		 * Manage share links
		 */
		manage_share_links: () => LocalizedString
	}
	/**
	 * User
	 */
	user: () => LocalizedString
	/**
	 * Status
	 */
	status: () => LocalizedString
	/**
	 * Add
	 */
	add: () => LocalizedString
	/**
	 * Remove
	 */
	remove: () => LocalizedString
}

export type Formatters = {}
